// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4jurx6bQfXXgXalBCpyd_iTh8AtfYpA',
    appId: '1:618191589644:web:eb620edc02e325c880f929',
    messagingSenderId: '618191589644',
    projectId: 'nxc-badge-a42f6',
    authDomain: 'nxc-badge-a42f6.firebaseapp.com',
    storageBucket: 'nxc-badge-a42f6.firebasestorage.app',
    measurementId: 'G-K92YFB4YBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm4jurx6bQfXXgXalBCpyd_iTh8AtfYpA',
    appId: '1:618191589644:android:YOUR_ANDROID_APP_ID', // You'll need to add Android app to Firebase
    messagingSenderId: '618191589644',
    projectId: 'nxc-badge-a42f6',
    storageBucket: 'nxc-badge-a42f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm4jurx6bQfXXgXalBCpyd_iTh8AtfYpA',
    appId: '1:618191589644:ios:YOUR_IOS_APP_ID', // You'll need to add iOS app to Firebase
    messagingSenderId: '618191589644',
    projectId: 'nxc-badge-a42f6',
    storageBucket: 'nxc-badge-a42f6.firebasestorage.app',
    iosBundleId: 'com.example.testApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm4jurx6bQfXXgXalBCpyd_iTh8AtfYpA',
    appId: '1:618191589644:ios:YOUR_MACOS_APP_ID', // You'll need to add macOS app to Firebase
    messagingSenderId: '618191589644',
    projectId: 'nxc-badge-a42f6',
    storageBucket: 'nxc-badge-a42f6.firebasestorage.app',
    iosBundleId: 'com.example.testApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm4jurx6bQfXXgXalBCpyd_iTh8AtfYpA',
    appId: '1:618191589644:web:eb620edc02e325c880f929', // Using web config for Windows
    messagingSenderId: '618191589644',
    projectId: 'nxc-badge-a42f6',
    authDomain: 'nxc-badge-a42f6.firebaseapp.com',
    storageBucket: 'nxc-badge-a42f6.firebasestorage.app',
    measurementId: 'G-K92YFB4YBT',
  );
}
